/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncCarousel: typeof import('./src/components/common/AsyncCarousel.vue')['default']
    AsyncState: typeof import('./src/components/common/AsyncState.vue')['default']
    BaseLogo: typeof import('./src/components/layout/BaseLogo.vue')['default']
    BookingDetailDialog: typeof import('./src/components/user/BookingDetailDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    CalendarSyncDialog: typeof import('./src/components/common/CalendarSyncDialog.vue')['default']
    CancelBookingDialog: typeof import('./src/components/user/CancelBookingDialog.vue')['default']
    CardPurchaseDialog: typeof import('./src/components/user/CardPurchaseDialog.vue')['default']
    CourseCard: typeof import('./src/components/user/CourseCard.vue')['default']
    CourseCarousel: typeof import('./src/components/user/CourseCarousel.vue')['default']
    CourseDetail: typeof import('./src/components/user/CourseDetail.vue')['default']
    DateRangeFilter: typeof import('./src/components/common/DateRangeFilter.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HistoryDialog: typeof import('./src/components/user/HistoryDialog.vue')['default']
    InterestsSelectionDialog: typeof import('./src/components/user/InterestsSelectionDialog.vue')['default']
    LineLoginButton: typeof import('./src/components/auth/LineLoginButton.vue')['default']
    LoginDialog: typeof import('./src/components/user/LoginDialog.vue')['default']
    MerchantHeader: typeof import('./src/components/layout/MerchantHeader.vue')['default']
    MerchantSidebar: typeof import('./src/components/layout/MerchantSidebar.vue')['default']
    PaymentDialog: typeof import('./src/components/user/PaymentDialog.vue')['default']
    PurchaseDialog: typeof import('./src/components/user/PurchaseDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/layout/SearchBar.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
