/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncCarousel: typeof import('./src/components/common/AsyncCarousel.vue')['default']
    AsyncState: typeof import('./src/components/common/AsyncState.vue')['default']
    BaseLogo: typeof import('./src/components/layout/BaseLogo.vue')['default']
    BookingCard: typeof import('./src/components/BookingCard.vue')['default']
    CourseCard: typeof import('./src/components/modal/CourseCard.vue')['default']
    CourseCarousel: typeof import('./src/components/modal/CourseCarousel.vue')['default']
    CourseDetail: typeof import('./src/components/user/CourseDetail.vue')['default']
    DateRangeFilter: typeof import('./src/components/common/DateRangeFilter.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HistoryDialog: typeof import('./src/components/user/HistoryDialog.vue')['default']
    InterestsSelectionDialog: typeof import('./src/components/user/InterestsSelectionDialog.vue')['default']
    LoginDialog: typeof import('./src/components/auth/LoginDialog.vue')['default']
    MerchantHeader: typeof import('./src/components/layout/MerchantHeader.vue')['default']
    MerchantSidebar: typeof import('./src/components/layout/MerchantSidebar.vue')['default']
    PaymentDialog: typeof import('./src/components/payment/PaymentDialog.vue')['default']
    PurchaseDialog: typeof import('./src/components/user/PurchaseDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/layout/SearchBar.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
  }
}
