/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLogo: typeof import('./src/components/layout/BaseLogo.vue')['default']
    CourseCard: typeof import('./src/components/modal/CourseCard.vue')['default']
    DateRangeFilter: typeof import('./src/components/common/DateRangeFilter.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    PaymentDialog: typeof import('./src/components/payment/PaymentDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/layout/SearchBar.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
  }
}
